apiVersion: v1
data:
  {{ .Values.firebase.admin_service_account_key_filename | default "serviceAccountKey.json" }}: {{ .Values.firebase.service_account_secret_material }}
kind: Secret
metadata:
  name: {{ .Chart.AppVersion }}-{{ .Values.global.stage | default "develop" }}-firebase-bundle
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
