kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: job-liquibase-log-claim
spec:
{{- if .Values.job-liquibase.storage_class_name }}
  storageClassName: {{ .Values.job-liquibase.storage_class_name | quote }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
