apiVersion: v1
kind: Service
metadata:
  name: analysis-actuator
  labels:
    app: analysis
    stage: {{ .Values.global.stage | default "develop" }}
spec:
  type: NodePort
  ports:
  - name: "actuator"
    port: 9080
    protocol: TCP
    nodePort: {{ .Values.nodePorts.analysis_actuator | default "31011" }}
  selector:
    app: analysis
    stage: {{ .Values.global.stage | default "develop" }}
