apiVersion: v1
kind: Service
metadata:
  name: batch-actuator
  labels:
    app: batch
    stage: {{ .Values.global.stage | default "develop" }}
spec:
  type: NodePort
  ports:
  - name: "actuator"
    port: 9080
    protocol: TCP
    nodePort: {{ .Values.nodePorts.batch_actuator | default "31013" }}
  selector:
    app: batch
    stage: {{ .Values.global.stage | default "develop" }}
