/*******************************************************************************
 * Copyright (c) 2016 Stichting Yona Foundation This Source Code Form is subject to the terms of the Mozilla Public License, v.
 * 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *******************************************************************************/
package nu.yona.server.subscriptions.entities;

import java.time.ZonedDateTime;
import java.util.Optional;
import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;

import nu.yona.server.crypto.CryptoSession;
import nu.yona.server.crypto.CryptoUtil;
import nu.yona.server.crypto.StringFieldEncrypter;
import nu.yona.server.entities.EntityWithID;
import nu.yona.server.entities.RepositoryProvider;
import nu.yona.server.subscriptions.service.DeviceRequestException;

/*
 * A request to add another device for an existing user. The data cannot be encrypted with the 'yona password' key because that is
 * stored on the device and cannot be entered by the user. Therefore we have to transfer the 'yona password' over the server to
 * the new device and obviously encrypt it (with a temporary password entered by the user, e.g. a one time password generated by
 * the app) while stored on the server.
 */
@Entity
@Table(name = "NEW_DEVICE_REQUESTS")
public class NewDeviceRequest extends EntityWithID
{
	public static NewDeviceRequestRepository getRepository()
	{
		return (NewDeviceRequestRepository) RepositoryProvider.getRepository(NewDeviceRequest.class, UUID.class);
	}

	private static final String DECRYPTION_CHECK_STRING = "Decrypted properly#";

	@Transient
	private String decryptionCheck;
	private String decryptionCheckCipherText;

	private ZonedDateTime creationDateTime;

	@Transient
	private String yonaPassword;
	private String yonaPasswordCipherText;

	private byte[] initializationVector;

	@JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSZ")
	public ZonedDateTime getCreationTime()
	{
		return creationDateTime;
	}

	public String getYonaPassword()
	{
		return yonaPassword;
	}

	// Default constructor is required for JPA
	public NewDeviceRequest()
	{
		super(null);
	}

	private NewDeviceRequest(UUID id, String yonaPassword, ZonedDateTime creationDateTime)
	{
		super(id);
		this.yonaPassword = yonaPassword;
		this.creationDateTime = creationDateTime;
		this.decryptionCheck = buildDecryptionCheck();
	}

	public static NewDeviceRequest createInstance(String yonaPassword)
	{
		return new NewDeviceRequest(UUID.randomUUID(), yonaPassword, ZonedDateTime.now());
	}

	private static String buildDecryptionCheck()
	{
		return DECRYPTION_CHECK_STRING + CryptoUtil.getRandomString(DECRYPTION_CHECK_STRING.length());
	}

	private boolean isDecrypted()
	{
		return decryptionCheck != null;
	}

	public boolean isDecryptedProperly()
	{
		return isDecrypted() && decryptionCheck.startsWith(DECRYPTION_CHECK_STRING);
	}

	public void encryptYonaPassword(String newDeviceRequestPassword)
	{
		CryptoSession.execute(Optional.of(newDeviceRequestPassword), null, () -> {
			this.initializationVector = CryptoSession.getCurrent().generateInitializationVector();
			CryptoSession.getCurrent().setInitializationVector(this.initializationVector);
			this.yonaPasswordCipherText = new StringFieldEncrypter().convertToDatabaseColumn(this.yonaPassword);
			this.decryptionCheckCipherText = new StringFieldEncrypter().convertToDatabaseColumn(this.decryptionCheck);
			return null;
		});
	}

	public void decryptYonaPassword(String newDeviceRequestPassword, String mobileNumber)
	{
		CryptoSession.execute(Optional.of(newDeviceRequestPassword), null, () -> {
			CryptoSession.getCurrent().setInitializationVector(this.initializationVector);
			this.yonaPassword = new StringFieldEncrypter().convertToEntityAttribute(this.yonaPasswordCipherText);
			this.decryptionCheck = new StringFieldEncrypter().convertToEntityAttribute(this.decryptionCheckCipherText);
			return null;
		});

		if (!this.isDecryptedProperly())
		{
			throw DeviceRequestException.invalidNewDeviceRequestPassword(mobileNumber);
		}
	}
}
