databaseChangeLog:
- changeSet:
    id: 1480156296243-1
    author: Bert (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: JOB_EXECUTION_ID
            type: BIGINT
        - column:
            name: VERSION
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: JOB_INSTANCE_ID
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: CREATE_TIME
            type: datetime(6)
        - column:
            name: START_TIME
            type: datetime(6)
        - column:
            name: END_TIME
            type: datetime(6)
        - column:
            name: STATUS
            type: VARCHAR(10)
        - column:
            name: EXIT_CODE
            type: VARCHAR(2500)
        - column:
            name: EXIT_MESSAGE
            type: VARCHAR(2500)
        - column:
            name: LAST_UPDATED
            type: datetime(6)
        - column:
            name: JOB_CONFIGURATION_LOCATION
            type: VARCHAR(2500)
        tableName: BATCH_JOB_EXECUTION
- changeSet:
    id: 1480156296243-2
    author: Bert (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: JOB_EXECUTION_ID
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: SHORT_CONTEXT
            type: VARCHAR(2500)
        - column:
            name: SERIALIZED_CONTEXT
            type: TEXT
        tableName: BATCH_JOB_EXECUTION_CONTEXT
- changeSet:
    id: 1480156296243-3
    author: Bert (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: JOB_EXECUTION_ID
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: TYPE_CD
            type: VARCHAR(6)
        - column:
            constraints:
              nullable: false
            name: KEY_NAME
            type: VARCHAR(100)
        - column:
            name: STRING_VAL
            type: VARCHAR(250)
        - column:
            name: DATE_VAL
            type: datetime(6)
        - column:
            name: LONG_VAL
            type: BIGINT
        - column:
            name: DOUBLE_VAL
            type: DOUBLE
        - column:
            constraints:
              nullable: false
            name: IDENTIFYING
            type: CHAR(1)
        tableName: BATCH_JOB_EXECUTION_PARAMS
- changeSet:
    id: 1480156296243-4
    author: Bert (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: ID
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: UNIQUE_KEY
            type: CHAR(1)
        tableName: BATCH_JOB_EXECUTION_SEQ
- changeSet:
    id: 1480156296243-5
    author: Bert (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: JOB_INSTANCE_ID
            type: BIGINT
        - column:
            name: VERSION
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: JOB_NAME
            type: VARCHAR(100)
        - column:
            constraints:
              nullable: false
            name: JOB_KEY
            type: VARCHAR(32)
        tableName: BATCH_JOB_INSTANCE
- changeSet:
    id: 1480156296243-6
    author: Bert (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: ID
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: UNIQUE_KEY
            type: CHAR(1)
        tableName: BATCH_JOB_SEQ
- changeSet:
    id: 1480156296243-7
    author: Bert (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: STEP_EXECUTION_ID
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: VERSION
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: STEP_NAME
            type: VARCHAR(100)
        - column:
            constraints:
              nullable: false
            name: JOB_EXECUTION_ID
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: START_TIME
            type: datetime(6)
        - column:
            name: END_TIME
            type: datetime(6)
        - column:
            name: STATUS
            type: VARCHAR(10)
        - column:
            name: COMMIT_COUNT
            type: BIGINT
        - column:
            name: READ_COUNT
            type: BIGINT
        - column:
            name: FILTER_COUNT
            type: BIGINT
        - column:
            name: WRITE_COUNT
            type: BIGINT
        - column:
            name: READ_SKIP_COUNT
            type: BIGINT
        - column:
            name: WRITE_SKIP_COUNT
            type: BIGINT
        - column:
            name: PROCESS_SKIP_COUNT
            type: BIGINT
        - column:
            name: ROLLBACK_COUNT
            type: BIGINT
        - column:
            name: EXIT_CODE
            type: VARCHAR(2500)
        - column:
            name: EXIT_MESSAGE
            type: VARCHAR(2500)
        - column:
            name: LAST_UPDATED
            type: datetime(6)
        tableName: BATCH_STEP_EXECUTION
- changeSet:
    id: 1480156296243-8
    author: Bert (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: STEP_EXECUTION_ID
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: SHORT_CONTEXT
            type: VARCHAR(2500)
        - column:
            name: SERIALIZED_CONTEXT
            type: TEXT
        tableName: BATCH_STEP_EXECUTION_CONTEXT
- changeSet:
    id: 1480156296243-9
    author: Bert (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: ID
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: UNIQUE_KEY
            type: CHAR(1)
        tableName: BATCH_STEP_EXECUTION_SEQ
- changeSet:
    id: 1480156296243-10
    author: Bert (generated)
    changes:
    - addPrimaryKey:
        columnNames: JOB_EXECUTION_ID
        tableName: BATCH_JOB_EXECUTION
- changeSet:
    id: 1480156296243-11
    author: Bert (generated)
    changes:
    - addPrimaryKey:
        columnNames: JOB_EXECUTION_ID
        tableName: BATCH_JOB_EXECUTION_CONTEXT
- changeSet:
    id: 1480156296243-12
    author: Bert (generated)
    changes:
    - addPrimaryKey:
        columnNames: JOB_INSTANCE_ID
        tableName: BATCH_JOB_INSTANCE
- changeSet:
    id: 1480156296243-13
    author: Bert (generated)
    changes:
    - addPrimaryKey:
        columnNames: STEP_EXECUTION_ID
        tableName: BATCH_STEP_EXECUTION
- changeSet:
    id: 1480156296243-14
    author: Bert (generated)
    changes:
    - addPrimaryKey:
        columnNames: STEP_EXECUTION_ID
        tableName: BATCH_STEP_EXECUTION_CONTEXT
- changeSet:
    id: 1480156296243-15
    author: Bert (generated)
    changes:
    - addUniqueConstraint:
        columnNames: JOB_NAME, JOB_KEY
        constraintName: JOB_INST_UN
        tableName: BATCH_JOB_INSTANCE
- changeSet:
    id: 1480156296243-16
    author: Bert (generated)
    changes:
    - addUniqueConstraint:
        columnNames: UNIQUE_KEY
        constraintName: UNIQUE_KEY_UN
        tableName: BATCH_JOB_EXECUTION_SEQ
- changeSet:
    id: 1480156296243-17
    author: Bert (generated)
    changes:
    - addUniqueConstraint:
        columnNames: UNIQUE_KEY
        constraintName: UNIQUE_KEY_UN
        tableName: BATCH_JOB_SEQ
- changeSet:
    id: 1480156296243-18
    author: Bert (generated)
    changes:
    - addUniqueConstraint:
        columnNames: UNIQUE_KEY
        constraintName: UNIQUE_KEY_UN
        tableName: BATCH_STEP_EXECUTION_SEQ
- changeSet:
    id: 1480156296243-19
    author: Bert (generated)
    changes:
    - createIndex:
        columns:
        - column:
            name: JOB_EXECUTION_ID
        indexName: JOB_EXEC_PARAMS_FK
        tableName: BATCH_JOB_EXECUTION_PARAMS
- changeSet:
    id: 1480156296243-20
    author: Bert (generated)
    changes:
    - createIndex:
        columns:
        - column:
            name: JOB_EXECUTION_ID
        indexName: JOB_EXEC_STEP_FK
        tableName: BATCH_STEP_EXECUTION
- changeSet:
    id: 1480156296243-21
    author: Bert (generated)
    changes:
    - createIndex:
        columns:
        - column:
            name: JOB_INSTANCE_ID
        indexName: JOB_INST_EXEC_FK
        tableName: BATCH_JOB_EXECUTION
- changeSet:
    id: 1480156296243-22
    author: Bert (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: JOB_EXECUTION_ID
        baseTableName: BATCH_JOB_EXECUTION_CONTEXT
        constraintName: JOB_EXEC_CTX_FK
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: JOB_EXECUTION_ID
        referencedTableName: BATCH_JOB_EXECUTION
- changeSet:
    id: 1480156296243-23
    author: Bert (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: JOB_EXECUTION_ID
        baseTableName: BATCH_JOB_EXECUTION_PARAMS
        constraintName: JOB_EXEC_PARAMS_FK
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: JOB_EXECUTION_ID
        referencedTableName: BATCH_JOB_EXECUTION
- changeSet:
    id: 1480156296243-24
    author: Bert (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: JOB_EXECUTION_ID
        baseTableName: BATCH_STEP_EXECUTION
        constraintName: JOB_EXEC_STEP_FK
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: JOB_EXECUTION_ID
        referencedTableName: BATCH_JOB_EXECUTION
- changeSet:
    id: 1480156296243-25
    author: Bert (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: JOB_INSTANCE_ID
        baseTableName: BATCH_JOB_EXECUTION
        constraintName: JOB_INST_EXEC_FK
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: JOB_INSTANCE_ID
        referencedTableName: BATCH_JOB_INSTANCE
- changeSet:
    id: 1480156296243-26
    author: Bert (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: STEP_EXECUTION_ID
        baseTableName: BATCH_STEP_EXECUTION_CONTEXT
        constraintName: STEP_EXEC_CTX_FK
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: STEP_EXECUTION_ID
        referencedTableName: BATCH_STEP_EXECUTION
- changeSet:
    id: 1480156296243-27
    author: Bert (manually created)
    changes:
    - insert:
        tableName: BATCH_STEP_EXECUTION_SEQ
        columns:
        - column:
            name: ID
            value: 0
        - column:
            name: UNIQUE_KEY
            value: "0"
    - insert:
        tableName: BATCH_JOB_EXECUTION_SEQ
        columns:
        - column:
            name: ID
            value: 0
        - column:
            name: UNIQUE_KEY
            value: "0"
    - insert:
        tableName: BATCH_JOB_SEQ
        columns:
        - column:
            name: ID
            value: 0
        - column:
            name: UNIQUE_KEY
            value: "0"
