# Default values for yona-server
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

#Installs mysql and ldap
support_infrastructure:
  enabled: true

#Installs hazelcast server
deploy_hazelcast:
  enabled: true

global:
  stage: develop
  imagebase: yonadev

# Attempt tries in seed/update container before exit.  Not k8s job retry
# This just reduces the 'failed' jobs spam in pod list until services
# come online (5 second delay on curl, 2 on sql)
seed_max_tries: 3

istio:
  enabled: false

vpn:
  remote: "vpn.yona.local 443"
  # Note - This is the VPN CA, not HTTPS Inspection CA
  ca: |
    -----BEGIN CERTIFICATE-----
    MIICdDCCAd2gAwIBAgIJAKHlBds0knLfMA0GCSqGSIb3DQEBCwUAMDExEzARBgNV
    BAMTCnlvbmEtZ3cwMDMxDTALBgNVBAoTBFlvbmExCzAJBgNVBAYTAk5MMB4XDTE1
    MTAyNDE4NDAxNVoXDTIzMTAyMjE4NDAxNVowMTETMBEGA1UEAxMKeW9uYS1ndzAw
    MzENMAsGA1UEChMEWW9uYTELMAkGA1UEBhMCTkwwgZ8wDQYJKoZIhvcNAQEBBQAD
    gY0AMIGJAoGBAM9iCyAcl67qerg9IYbkFUDTxG73hhUTqglDA7GkDv0Q8AUK6sFN
    gKgIKyQ4Qy4QuqVeunTwHP1LVlNk1rIu9QNKAxL90B8u5n7UO7B6ASkTokOd1aD0
    jxN9FVJZPcejyqnr12R+uzBW3N1ZK87J/hS5aaKhDu535QN0yEZRO0LtAgMBAAGj
    gZMwgZAwHQYDVR0OBBYEFD7+oDI0SxNHItX1CBsh79qZ7nLSMGEGA1UdIwRaMFiA
    FD7+oDI0SxNHItX1CBsh79qZ7nLSoTWkMzAxMRMwEQYDVQQDEwp5b25hLWd3MDAz
    MQ0wCwYDVQQKEwRZb25hMQswCQYDVQQGEwJOTIIJAKHlBds0knLfMAwGA1UdEwQF
    MAMBAf8wDQYJKoZIhvcNAQELBQADgYEAx671Cv4urGpLGrH21bdGjR29qEUYGwU9
    +qWWNiFHSiu+1928Ix1wun2NMKIDQWQ/zsCy/NtUhajK5lonvYVfsmcLCIqveAEV
    k01xnwm210/pltMc43SOQDc8uc9wzMVo5az1+KRFqX6tNWX0YcKiMZJYIBLnW1LV
    MQ9Zm4u00bA=
    -----END CERTIFICATE-----
  # Note - No BEGIN or END stanza in the user cert below.
  # because it is used in mobiconfig outside of the OpenVPN section
  cert: |
    MIIJoQIBAzCCCWcGCSqGSIb3DQEHAaCCCVgEgglUMIIJUDCCBAcG
    CSqGSIb3DQEHBqCCA/gwggP0AgEAMIID7QYJKoZIhvcNAQcBMBwG
    CiqGSIb3DQEMAQYwDgQI8xlN9q7y4TQCAggAgIIDwEbWTpSiBKdx
    r9vh5zQQIoUjw2yUm/iRZqIpkyf11AZ0cMw2DlwVrFTa2M8TaBVa
    AZx0wuVZ6p3M2I5RRPaGwc/N2Bz9S+hB9TKnTWK8Hc+e925Berja
    yR7iwp2gcWya+gM1nkc5LRgSs8ZaEw+k3UgGNltNCvFIgDVBJxRb
    0iJ23sVicWYEKNSo4BrxSmFBhbIGH9QujRYntMYhKGXNsE4R4Q+d
    Q79LK7CWrP8a+70P4bEElTbubkZUPNd+iAX/KliqYV5xyCL39xn4
    +uk03NCsHEYNVAY2HL607gdNGnBI+bDV6LV6coqWEXisHAcb7Sxq
    T2ybqnqJ6NJToCDIbGxIELrboMaVhaTLUWcOYu2Im9nE6YBnDqEj
    YPQLRKjNrRZEZ/bUJHgycW6PxUoRXgeQet1DKcdXKevMLefsvDwE
    9BIxhZUqZOoWtv4V10yz7JUgj/cV8aXOawW/WaBH1Z7NfAx9RWMH
    XxKCGVAlz3sgyQuvgVUtJAddLPu3iegpvfvO+Td4VNLXf/SHolL+
    l5Cp3ayUwO2eMN94sLNXX/41TgOkc504afUR9MVhFxTq9XeMxA18
    mXIpSc2fzuqmUIDheR2lgg/5ntmsJn/VRbM8JjIGznIf6xYlJMAB
    cbohuJr75MjDxXRnVJWaYAr5KR/hpxkbhJ8HlyDaaPOAHUlHjp4K
    Xg3K6ynrL4kVgmb+LyW6SXz0FqJ6A6aQjI63j7eQ7plREJETsfJa
    PjpMmMJ646vSG1f+c8I0lyfNu3F8OYnDFpf7Oc1y/lDCVOHs3mMk
    sSuUSQYNffF+sQ6hOFXIfa0hKyzMzzfSdXd0cmueQZUHJLOis9QZ
    9iUdQYzidxX/8nvMJ4SBtC/I6R7aRcKW3EtZ59lL7IdxFt02psBd
    CimTnKGtiP7NTfyEKbkCh9FeXCyLGg6uB6rx3YJOWl4KwULe82fC
    YiqVtg6/tghieKijjMFfxy3qSzHAuMFYxhR1lEGmv50YL6/viA1Z
    +5z5+GMRCjGYpYm2i2PuCm3dnpCxgduxZgUQujMsP/+Qd77arEiK
    t6lyfTG7HaAkG//12ifW9Ix2+8oIWc5pG6IHDtGlEFJVgs3cYOPQ
    RX8PVPUeZKNsoNSJZ+F9cN28phKOkPMxtYED5DKOEVI2ztPkIDWc
    X3I/QkvB4mG3vbpV7V4/hK1ax6s81rRpfDxtAHI07OjmA/oVDQDs
    HXj5eJAoIK/5XA8jNKCcXp8TncTjH+IMXMknvnry1BIRYmm8B6GY
    lFNZ/MgiOrHJZjF6Zu1H/TCCBUEGCSqGSIb3DQEHAaCCBTIEggUu
    MIIFKjCCBSYGCyqGSIb3DQEMCgECoIIE7jCCBOowHAYKKoZIhvcN
    AQwBAzAOBAigGAF/W/pXBwICCAAEggTI/kzvksPa6HChycG6M2/e
    nAJ6shxQX4ul0edWkF/upg8fGJHrdbDqPS+AZUM/OeV/zFQ4oju+
    g4DRQ7lJW3ENsh6NFZbbgoAyIXIrV3N6dAYYt9Bs9HDkgTOGuVxK
    3RyJZnjZyXJmigXcNsdIPqGka4ogfB1d6NxzG+2l4at2z212HaSH
    sD3lJPqPIAtgT3M3KQC8SSby8BWKkKdb7jCgwSF/NcAztP7ZPddm
    45qNZc/2S/sgugbrp5ftDEIWYP6HN0nPph44HQR+Wdp7OED7Sk6j
    gIxxpp59u4UiR68LynPYsse+LLSiMDtFenIeBhBO0E6HCo4VHxwb
    WHsTxU2HF3Ai0WuG69mCkVn0p3G1ON1q3TNp2KHF8tGWN4JnqN5O
    7yQWGHUo56k929+cKIP5FabESrYSiJBv013akxHYMLZcW9VFXwPv
    aKPTt7JnvIfC/AA6m3FDBL5UWsnuT8KMdhE7fnNWwijAtVZYISbj
    JojxhT5v1z1qCrNlftFACq/rI/anXtd3y04vQOQsJXPeZf4R02uv
    SPQ5i4F0/jZ6YH386Z/4xhd/57DpeCdU6hv1hDi+N18Plvbq8jbL
    uSAypvjry+cllIQ0u3oiOIPzeMhT3DXnL5CmentuWuiP9AoZ4MKS
    /lvXIYYWCpIfPrWISYXXdUgIQfU+NdPxOxm1tAASCFD4Mp7Xj5l9
    yZb0J7wKch2Nkq9wJeluShe+IIJ1sHc+PA+YfSYnmmVmqPxp5oUn
    ZPKdlpLJYuQglIDznyXf4tP1eMxRIunYYTFj+/9BmIAxVY0wm6DL
    HfZ7ioyEgENAUZuc/nn7/75QzmnrbIhY+RCgUEMNH4asMxLacYwU
    ulb+9fv3Bgy8FHGFluyx+qOdvFDkrfGZJecSxrzjZq7zf6J9dXau
    uXoHqUWNu4Nn+8MY4lONqRIMNBL17UP3d92tZ2P2DH0FqUksyGdb
    ePe2QNCLTxhlopQ+ft7CYS2rBVTzTWvUHL8CN56R05N6O1irWU14
    63EcwtkE8SgUMB5xMrHa8XBuen/AZDu3UKdkfUqBjgZKWxTAUP7Z
    XOZflUFL4K1qVTeBQyVFaj3QO6q1mPzo5fbKb72m6B61KxgCAVRN
    k102d7Y1/rQn8q2OchWwswcfMf5ryETmCWaRxJItIUw1nQ+pe7Td
    AtLzTpCkID3X/eK075JTrgOQd+VpRxADwo8h9/XH8ZSUkP1zLiqX
    GkZ6m4CBMP0+ay2Y0HYUYxXaePGFcdP1uCWjA+PpHql6wuN60xh3
    givBTI49QAog0pHjPaM/zi3Asn6Z74he2VY8wRLAtQvOWo4A3baU
    6AflOQ0ftunFJ73Jv6cjt214syr6plehO3JWE0qKD+aJgQu4jN6J
    i6XXPFTfNtOKOgU+TWtyTY40l/KSMPp7pO8hnTSP8ni9AOtjHCQV
    bBWfnVyGy/pszrmfNZ56UrRsRgQhKsOOJMxEDiKzVBfeGDeQngJR
    dbFIPVHOkejg4bVFgCztwBXlilB1GK+Wzof4zuvHMOFOHI+xe2bd
    cFLB2PC7y/YXmGa7g8rph1vdS8vI6o7o8ROJzsB53lMf0oRlT7va
    AhOIkm/3wJYbLwTUXK9LPgatg3VIVfvxzXNMRkFiFdR8wd+126vo
    MSUwIwYJKoZIhvcNAQkVMRYEFLtvJjTZq6W9OPLhsrZ8SHeiRccm
    MDEwITAJBgUrDgMCGgUABBQq/UaovDPyN0M0VQ0voWeAa8x9qgQI
    rVw8cebTOqYCAggA
  cert_password: joepie
  tls_remote: "/C=NL/O=Yona/CN=yonauser"
  tls_auth: |
    -----BEGIN OpenVPN Static key V1-----
    106a6773b0c019f61c954784ad67b852
    74d82b712dd235e436950e17d019c2e8
    a4205bb809af417d85952bfc0c921cf5
    ec2547526584749ec079fe4e3ad5e0ec
    9f20d0b6a25c6535c21101f98c3af8e3
    44ad0e18bd04e96f2e4992fa1cbf7b23
    2255c535385a194a176003aad54c38c8
    62a3c98ede521f2a71e1fc8b348eb344
    3bdfad46bfb885d3888e39a3b4187cf5
    e6e6ef631f0b0ab3eb8210df58eeb379
    1b51a2886ea5dcdfa18d19100142516d
    a2a714cbca00d031371b6f972fc85e22
    5dd16fb22bbfb2841b9f8dd01a991069
    dddc18040c43776680f36a451a9c8e77
    63e1f19b2cf2f13bc3443ec54299f179
    0e653b2b4baa3765cbd533e906762224
    -----END OpenVPN Static key V1-----

email:
  enabled: false
  sender_address: noreply@yona.nu
  smtp_protocol: smtp
  smtp_host: smtp.example.com
  smtp_port: 587
  smtp_enable_auth: true
  smtp_enable_start_tls: true
  smtp_username: noreply@example.com
  smtp_password: "password"
  included_media_base_url: "https://app.dev.yona.nu/media/"

ldap:
  enabled: true
  org: "Yona Development"
  domain: "example.local"
  #url_override: "ldap://ldap.yona.svc.cluster.local:389"
  #hostname: ldap.yona.svc.cluster.local
  port: 389
  dn: "dc=example,dc=local"
  user_dn: "cn=admin,dc=example,dc=local"
  user_password: "ldappassword"
  config_password: "config"
  storage_class_name_ldap: standard
  storage_class_name_sldap: standard

sms:
  enabled: false
  default_sender_number: "+17184169858"
  alpha_sender_id: Yona
  alpha_sender_supporting_country_calling_codes: +31 +49 +33
  plivo_url: "https://api.plivo.com/v1/Account/{0}/Message/"
  plivo_auth_id: M1234123412341234123
  plivo_auth_token: N123412341234123412341234123412341234123
  
firebase:
  enabled: false
  admin_service_account_key_filename: serviceAccountKey.json
  service_account_secret_material: ZHVtbXlkdW1teWR1bW15
  admin_service_account_key_file: firebase/serviceAccountKey.json
  database_url: "https://yona-app.firebaseio.com"

apple:
  enabled: false
  keystore_secret_filename: dummy.p12
  keystore_secret_material: MIIQFAIBAzCCD9oGCSqGSIb3DQEHAaCCD8sEgg/HMIIPwzCCBd8GCSqGSIb3DQEHBqCCBdAwggXMAgEAMIIFxQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIbc/gNZQ2vAMCAggAgIIFmB7BwgPFGMV3HvpPT1xfhhnk4QI2qvVLUvx7NLhu1CkcvQIYVxujqCXX9jQ9R05lyiFvn8H8qd8Ltnk1UJoWyljNWsEOQl3VdogcuOF3b56KBaBL6uWmhRehaEBtOZHzzi5yEdrRcQkbyUynBROecLuVbHKo9iVAnvttNc5zx0MNLxIi4RZq9/+KTsVsHia/GOweh7kPlEWwQmyx9I7CXYQkQbiO1AbB3zRMd+/NySE0e707rg/zV9exKWX/YRH90SUuwyhwuxqYXjWqzK6r7i9KW+dwohAkvzuv5w29NrQ1azn1iDPN13junrpYsU9Qmges3Dpd2izIhpbX5NAoLFamEF5cFZplvDfxpmrcj00OUKUwtjlhW3p4RyfsF3O8apbWOUwfc8+6p9wMf+6s6rywd/I1IX0TnfD7rXcRZNSyLYJm8Xe1t5WzqJthw6TXqRMlQ7EzKUr2YnZCcRER3Zzwwnvib81gUk02zdA2IZSLxYza4YVKqMHb11kOJGn5UM4R8FHZ9uxXERNxyfCW2JiQbskBSykeV1Z+DNw66akYnUUFMXa4GohcwSbMaCf9LOGdNCkuoZuMGeFIRxmjRN0uZa5MA5mo8O83JqSz8hPVV9X/ywFZU1od1pOsLUwZkK/QtPp9S1gODdiFd0Qkth7bjw0Qygss4hqiKM62q3jPi9l0oer/my3wmR2VHO5Q0cCMeAsFVW2EjgH0ICf0H+wcK4u3rwbuywQtgpVVP+meyjfCpgpMbSgy7mkPaBK4XohK2UoDBctNJtVpX8R86IpKT8IwIGH8eDzkc85OuuAJAC/WmDUdcvWJpTSRx6diYXDM982tRvYfg2oCvHofz9A0HkI7VcG+cnMNi0ggYLr1MfOlJlX0s1KIuWsFiIuXZt+KFk5ZUVzJWrO7elou+m9mItXXIUyWcCy0VyAsOAgz9tuGBc2+EqZOe/Op5V3Z+BzsENAtjBsbfgdZ62+1rejsVJ3uesvY6wh21hBu9HWy4j8xeuYU7vRupuN2Velq5LscQK9dzFO0lRkwp1Drg1tf83w10x41/FZS0LLkY/n+Nzbf3Jb2L/SwmDOWMhjCcUx3sDc5Xb2k7b08cjjUxrCgmJnMc740rGjGjJMXsgtqIZPD94zqW5GQoDYuicBdW3c2rROcoMhPqpyscBwjCMKCvsvVpFOMkJYAqlbZs8lNabMrC/v+wJd8ZrqYnt4prIzNty405FMjEZrGPW98ovs9RttiWELIma90LndBlpFkwyTrOsUEYNSImvomil1SuxJ623APHowosyKo3G/sIXlIpbpf40hbJRVy6AS9vEa7yRwMuF4IlZVg8fgUJSQjR4SaoZ/0kcZbGobYcVaOow9Cm3PeGne9nwCxKMtCXHFRbbBewEIqPCQM3gzKkXmKJMVfaHwdEqxLolzcK+e4ocRi4st62x/CFORq1SguDX8R5udcvxLLLkDVpWu4c9OYVvfize00Gdk4FI9kMCnH3vn0i1EZN3V2PZAgtKHAJwy1L/wANjyMBl3z4D4FGyKhivlw58GELLv6cVixm2cGYIVPzQkmhDpO4cEBsgdjt5KqYX5R2TnmCrGSQB1s5/eU4msDzviLCVRrorXOzFvuVUnd/leE/q3KQGGbM5RQ/wuOmLSCENRsUwyaBnnA2DsvnaG80WPx1IZWSG4t/zlTXFzPuLCDx+3hza+tFcOndNvCXBb+fho6WhYwRDD3lcDck8LUgfxEWvTfDZ4jJgp8dzcj7QwLP5o4ZZvqMvKrtK7l8EPiTCT3+uaVUVoI/s+lZOoKbqRiIbc5JUEF0k0SN1HAeEQgMTLu6GPCFlEJIAaC2i+D5MJLVJGdeRJQUo1PVR28SD3QToyOCLT99KoJ0jliieLZjFUIQkdALm2irNVuI284GjhkP8swggncBgkqhkiG9w0BBwGgggnNBIIJyTCCCcUwggnBBgsqhkiG9w0BDAoBAqCCCW4wgglqMBwGCiqGSIb3DQEMAQMwDgQIxozcDQKkR5oCAggABIIJSPA/ZjjgBWnmYfRsW0SPaC1Wo5UiJ6SbyGJ88zmuUmlnONIHhDKndZq4y5MvKxn/x0uH9PGLIm2Zdyvh8upXDjiQVJFSUB/8We1ucKmniTuYpQRGk0KVGlKK++33sNemJkHTLfKwp1Cw5GWm+rKZ33OA3Jm0WDYh646ZjhWweB7B1ZoLY12DCV4fzihA2VCW0lA4/UKmGY3LEMhWXzCgQH8pmEBp30dtH0eeHnJhpTMVpuE4lT25s/vG5SK5il0N5C61I2A34huZ0n5/iKuC7+pEhJUzgjMl9/L55JlVqTwPllhum0Dp/JrYCTOaXWzJKvYk/pyvzv5FWQH1XFKKAanBt5FKGrlOdvyX4DmYoUIzue71PVkfV/d0wIXTlnOAsyp75STAxPIeT7YLucC3MJiJddN4DbtGdTfhbz0DOH4GYRTeAzdzx6S8F4gc6vDt4RtDFnbBzBOhkGWUHBaWuU39Jc/rSG2HmhOhlYWkPwgMTMPSpgTGZA3hbcBxqdDlYl5q00zr8qRQQKJkdDMLwT22uog8VX9Hu12TVxLXWOvK/E7AQFq2ZqSGiHHJ9TIckXtUn1lRIbhJQ85OYO3ntPjRzAdDjlEM/+g+kCup+jocRNa1PEZIQIprI+vHt2Yp7PvCUy8JitZ01+OzFOelFom58qdi4+Jrwh92KyD0ys1whUEvhyZyCH5SxxPcXTtzPjp7TCvbu9FZPP4VJb5kIIPGWi40QVVbbDA3wiOZF1iD3FX9eN22m0nsgoLSq2RtshbYqDb7GLTIAcQEeCrK+yANu7FWb3twxHj/+rX95JpckjYisQi1W9mSa0hDGsQdgadePbx6uEGfF2IK+Ml8CacxWl3g4Ry4wqRuor7/fcgBeggS4+y8Ft7V6YKRs3dVlzB9Vnpkq5o/7uRps/2CyGi8+26DDW0ShwacfP7yz5rOb+VYcooUuhXgwBuIzLDrzqbkrpNdbdJm9NGN1QR3mPy2zUds076P+XfAsHeUdT95YvfYa4nOwHKHKaPRDiI45jR9hYuUtMqXaRyo28TklJ+D/FykHcZLYffwZInmM4xdQJf+pykypS89wEoB3Wv3BTTNA35smo6W7c2Rm6jrkNZd7/iz9yCk0WhQz49V0OlC27fQFHS6Pibawt/hJl4mjcXE9Zz4oF2G40gZzr8ZMYBIN457x9mqXwt2fXwundj3oyjYwyZE8ohPn+H10on/439nU6a631Wwu37pNCMFsOJRj56GMQS2ymdiiOvtXn3Rm9x1r1aNIUI6bIjh8CELB9APuZl5Hbe6mok8Kr+evM2fh+9pScx5/5w5tGCpBB9aA10t5jWPGDptPewRSZvCgUIMRXaph6eIVKhY1ZNEI0rrmHlZ9tERXxyW2joX+wlkEppmgHDKdFigWlvLHa7xSh+cTQH3+AQwwCZdVqm/+vLyNm2Qel45IsMlxVqdhQbs9VnpVsWGPi6FbhZ8fNKr7BRdvV7CEpy0ESD244FTmkJgxcWXQV1MyrB/jXIj3oNrBfNOtWOczGoUA11GY2RA30zjZrviwZ1j1bkLTx4P3bY+8ol+EXVP1tBP3RFVlIxLPZCadgQ95fS0IsPNMeTnc3A+PxIPch9Ab/1m0JDbz2h/M4PYiFesz+5O9o81n1zEbF1NH4CZN75pCFooB83CxgOXQtlg3bvL6QnmsGWe6fku72XFcF4/VIkMRqDhPImXdoDsvXtuSI/+5OU9JMnNCQhsbdNsjDbGFL9y3s+1Ax1zn/oxQeY3+IeygdFYZstXnSoh962ItpMGg0xyn5i6sFVTLVQduEDPCXgd/CadO7zPwLzfNKH0iNiTdmAJnLuYHb8ZH0ngSsQ36pnjPKnyINdCGlZ/zGo+BYAUnK2dO1DzEiug//ouDHJ0VV659isb8ionmRwKcNmNGNxby84SZLcHoCUUzT6jMQaqnY7IsCV3nPdQt5+8FT90xUF+8RT74r04GxpcCHq3B/bassQTtu4ytVcXf6phjgtzPWgS2r6wLHu+M8rQTQ190Q+1wyxfa1Qg5Oa8DDHI8EoYLIq7hMdyUpRICU1zEyIA4LvtQ9omuRVQ2JlQl+Kzw4nqJDXd6yBAvKGn/WZjNQZOP2NS+96VaVEsXWxdOyahXlZOeGWSTE1yB+6lL5E3VbN9NbpG8KVfcnOmt2Y2NHRtJ5NwZV988KeKZglokWe43Er9SUUDgFZpNyG0eN+kJkKh7RUH9ba3f/c3HV97avRm8IXDW83xrBx2TNCftqyI9/OHCyOMJyQQRIGwtQ3zWUOyhcWvRvi1xgvUiNiX0bLOKdGhtSLihwppLk7RIBcCbIRqgoZgfbo1wQal0lo/uaMeyTUK7VhWl5Se+HKx7arEcwzBIQScltnL/3FrgmArbU6h7BbG6LWStEbNf/OhrgOB6I7t+Gw6l57t3H5zf85OWOzbIUGwXwEPU3IRZ2AKttZFlxrs2s7x1R9H0bIVk5vIuyaSiwbT+aH2md+iLiERdT4qU2ta6pIgCqKnBrdqN7whUa4ax5iNgY2nek8tvmLEdLf5U5Yzprql6ZtpRDmcDw3ErDZQ+ofO5oudjaTAsNjylzRvJVkihyB2KDvkd19eUarSER2DKWvnHd2obozjW8+eD7aq94RSHkjRhJVyrbzmq/+Zaea7WUkl/mSTPSadjb4imSbW0Uaf3+9LTXcO3UBpdn6aO1AwMYYbynQ+87xjKikNGI62TIUbstCnP1ZCKU15CzG+47NGUCTDDxP+DgSEyc25LQAA9w+iEk3nGTO4kRDWa4ebLDKYPPCbKiskZjHlq8m1SKCAG5+C5oAst+kfRlm2dUf7n84vgv1/KaWmVUxnbXZL3RA8QJ2i1F/l9oVpE2MSVGZO17q3FdRgS7LB3No0Q/WkUQpdjKSnrZx9wn6kZ1rsi7+i+aUjV9oVA7KCxZ0g5cFVyjunD7Cbyt5LUbAKztGPyDNk7NZ61Q3yHENBX566NBokDlZf3d2SxipBTyWW11hGZdkhPJ2VsJLy2091YSNLNTXsj+tVOWqRANRyWQAKbe1G2tqrJYEyJ5uqf6qOW3rFU2JuxNtjyUZvBcZ6+gr+qdaKwozWbA/Ucg3gjszCTgRkPBw47CvMXKQB3sp2euE6t1h6KgfdvBMA7Z6EHwpmrZ96SXAS1HDB4tf58XgW0fqbKTFAMBkGCSqGSIb3DQEJFDEMHgoAZAB1AG0AbQB5MCMGCSqGSIb3DQEJFTEWBBQVmXABq8n1+i3/YMJePh6yTlk3oDAxMCEwCQYFKw4DAhoFAAQURpsZK3Y5CRB+i0Vg9t/MkRAqq28ECIq0Q8WYUZHOAgIIAA==
  keystore_file: apple/dummy.p12
  keystore_password: DummyPwd
  alias: dummy
  ca_certificate_file: apple/AppleWWDRCA.cer

mariadb:
  mariadbRootPassword: develop
  mariadbUser: develop
  mariadbPassword: develop
  mariadbDatabase: yona
  persistence:
    storageClass: standard
    size: 2Gi
  user: develop
  password: develop
  #url_override: "jdbc:mariadb://db.default.svc.cluster.local/yona"
  #hostname_override: yona-mariadb.yona.svc.cluster.local

spring:
  loglevel: info
  logpattern: "correlation.id=%X{yona.correlation.id} app.os=%X{yona.app.os} app.versionCode=%X{yona.app.versionCode} app.versionName=\"%X{yona.app.versionName}\" Marker:%marker %5p"
  hazelcast:
    loglevel: info
    config: /opt/app/config/hazelcast-client.xml

admin:
  act_categories_json_file : productionActivityCategories.json

analysis:
  #url_override: "http://analysis.default.svc.cluster.local"
  update_skip_window: PT1M

app:
  max_users: "1000000"
  test_server: false
  enable_hibernate_stats_allowed: false
  whitelist:
    active_free_signup: false
    active_invited_users: false
  security:
    pin_reset_request_confirmation_code_delay: PT10S
    dos_protection_enabled: false
    dos_protection_window: PT5M
    max_create_user_attempts_per_time_window: 2
    max_update_user_attempts_per_time_window: 2

batch:
  enabled: true
  #url_override: "http://analysis.default.svc.cluster.local"

certs:
  root: |
    MIIDGzCCAgOgAwIBAgIBBzANBgkqhkiG9w0BAQsFADAdMRswGQYDVQQDExJzbW9v
    dGh3YWxsMDAzLnlvbmEwIhgPMjAxNTEwMjQxODE2MjVaGA8yMDMwMTAyMDE4MTYy
    NVowHTEbMBkGA1UEAxMSc21vb3Rod2FsbDAwMy55b25hMIIBIjANBgkqhkiG9w0B
    AQEFAAOCAQ8AMIIBCgKCAQEA7lq9cbuXuV1EzJStVRSBTCk1oWUrXD2oD3tAhyP+
    k2WKrV+WGHROGHi/SdFXq1nlIcMFSxGH8vxzD3lD22QFtr5BH6j3p3YqchoQPZFi
    HxyQa4FXtueArMtGU5gLid6l3NZVrjud6+XXVMNoDR6DOI2c2JCi2Su1A80D5bJD
    2X0Ye+PKNfn0rESRBm3MDACqLhNz4kO4Pa4/FFhK5rF4VDSIACAqcOxq2O0dtSO1
    pSh/IisTN4TbcfxJq45PHru+eqDHOnisi2hVjTJ+JSQnvUO+0i0j8F8IL45t3Xmc
    94NcYs0AXhcqCa+gTGxiHlvlamBDlDZEdwPb1g+3BZ6CMQIDAQABo2IwYDAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdEQQWMBSCEnNtb290aHdhbGwwMDMueW9uYTAPBgNV
    HQ8BAf8EBQMDBwQAMB0GA1UdDgQWBBSgfJSRu3i8JXcHBcc4wWG2L6f6TTANBgkq
    hkiG9w0BAQsFAAOCAQEAFhV11EQEEknmG/xbGM1KCYmihsQGtonQt6vvMk0lCvvW
    ByFFV9mATxaNeNKQVKHNEhTHwsocrC6MAhwq11hujp6paniHLi9XE/Ab9wUrEw0U
    2C/QCRVB3+EZpozbadHrkAuDkBa2AyLOO1KzlLXutTsM9cOXukXtIjw2GV9acI3h
    E1atre3I6+sXDD1stfFZs6qKpphRaSwNSCnFOa5+mK1GtHbr0f/BbSTyop+nKVyt
    A+pewjPUaERijjkgaT2qygKCkQQ03iaLEz6jD1DKvY9NipcY2f8WBK+STNz6qAyp
    MCuIv7V26zjwX1P91NOo0s/htoxxxxDiv86nUuYW8A==

nodePorts: {}
  # Placeholder. Normally, we use the defaults configured in the services yamls
