apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
    stage: {{ .Values.global.stage | default "develop" }}
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8080
    protocol: TCP
    nodePort: 31001
  selector:
    app: admin
    stage: {{ .Values.global.stage | default "develop" }}
