apiVersion: v1
kind: Service
metadata:
  name: batch
  labels:
    app: batch
    stage: {{ .Values.global.stage | default "develop" }}
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8080
    protocol: TCP
    nodePort: 31004
  selector:
    app: batch
    stage: {{ .Values.global.stage | default "develop" }}
