apiVersion: v1
kind: Service
metadata:
  name: app-actuator
  labels:
    app: app
    stage: {{ .Values.global.stage | default "develop" }}
spec:
  type: NodePort
  ports:
  - name: "actuator"
    port: 9080
    protocol: TCP
    nodePort: 31013
  selector:
    app: app
    stage: {{ .Values.global.stage | default "develop" }}
