apiVersion: v1
kind: Service
metadata:
  name: admin-actuator
  labels:
    app: admin
    stage: {{ .Values.global.stage | default "develop" }}
spec:
  type: NodePort
  ports:
  - name: "actuator"
    port: 9080
    protocol: TCP
    nodePort: 31011
  selector:
    app: admin
    stage: {{ .Values.global.stage | default "develop" }}
