apiVersion: v1
kind: Service
metadata:
  name: analysis
  labels:
    app: analysis
    stage: {{ .Values.global.stage | default "develop" }}
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8080
    protocol: TCP
    nodePort: 31002
  selector:
    app: analysis
    stage: {{ .Values.global.stage | default "develop" }}
