apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.global.stage | default "develop" }}-batch
  labels:
    app: batch
    stage: {{ .Values.global.stage | default "develop" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    build: "{{ .Chart.AppVersion }}"
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: batch
        stage: {{ .Values.global.stage | default "develop" }}
    spec:
      containers:
        - name: batch
          image: 'yonadev/batchservice:build-{{ .Chart.AppVersion }}'
          imagePullPolicy: Always
          env:       
            - name: YONA_DB_USER_NAME
              value: {{ .Values.mariadb.mariadbUser | default "develop" | quote }}
            - name: YONA_DB_PASSWORD
              value: {{ .Values.mariadb.mariadbPassword | default "develop" | quote }}
            - name: YONA_DB_URL
            {{- if .Values.mariadb.url_override}}
              value: {{ .Values.mariadb.url_override | quote }}
            {{- else }}
              value: "jdbc:mariadb://{{ .Release.Name }}-mariadb.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.mariadb.mariadbDatabase }}"
            {{- end }}
          ports:
            - containerPort: 8080
            - containerPort: 9080
          volumeMounts:
            - name: config-volume
              mountPath: /opt/app/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.AppVersion }}-{{ .Values.global.stage | default "develop" }}-springboot



