apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.global.stage | default "develop" }}-admin
  labels:
    app: admin
    stage: {{ .Values.global.stage | default "develop" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    build: "{{ .Values.global.build }}"
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: admin
        stage: {{ .Values.global.stage | default "develop" }}
    spec:
      containers:
        - name: admin
          image: 'yonadev/adminservice:build-{{ .Values.global.build }}'
          imagePullPolicy: Always
          env:       
            - name: YONA_DB_USER_NAME
              value: {{ .Values.mariadb.mariadbUser | default "develop" | quote }}
            - name: YONA_DB_PASSWORD
              value: {{ .Values.mariadb.mariadbPassword | default "develop" | quote }}
            - name: YONA_DB_URL
            {{- if .Values.mariadb.url_override}}
              value: {{ .Values.mariadb.url_override | quote }}
            {{- else }}
              value: "jdbc:mariadb://{{ .Release.Name }}-mariadb.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.mariadb.mariadbDatabase }}"
            {{- end }}
            - name: YONA_BATCH_SERVICE_SERVICE_URL
            {{- if .Values.batch }}
              value: {{ .Values.batch.url_override | quote }}
            {{- else }}
              value: "http://batch.{{ .Release.Namespace }}.svc.cluster.local"
            {{- end }}
          ports:
            - containerPort: 8080
            - containerPort: 9080
          volumeMounts:
            - name: config-volume
              mountPath: /opt/app/config
            - name: profile-resources
              mountPath: /opt/app/resources
            - name: apple-resources
              mountPath: /opt/app/apple
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.global.build }}-{{ .Values.global.stage | default "develop" }}-springboot
        - name: profile-resources
          configMap:
            name: {{ .Values.global.build }}-{{ .Values.global.stage | default "develop" }}-resources
        - name: apple-resources
          hostPath:
            path: /opt/yona/resources/apple
