###########################################
# Configuration data container
###########################################
configuration:
  image: busybox
  volumes:
    - ./config:/config:ro

###########################################
# Logging: ELK stack copied from http://www.labouisse.com/how-to/2015/09/23/elk-docker-and-spring-boot/
###########################################

elasticsearch:
  image: elasticsearch:2.3.1
  restart: unless-stopped
  environment:
      TZ: Europe/Amsterdam
  volumes:
      - /usr/share/elasticsearch/data
  ports:
      - "9200:9200"

logstash:
  image: logstash:2.3.1
  restart: unless-stopped
  environment:
      TZ: Europe/Amsterdam
  ports:
      - "12201:12201"
      - "12201:12201/udp"
  volumes_from:
      - configuration:ro
  links:
      - elasticsearch:db
  command: logstash -f /config/gelf.conf

kibana:
  image: kibana:4.5.0
  restart: unless-stopped
  environment:
      TZ: Europe/Amsterdam
  links:
      - elasticsearch:elasticsearch
  ports:
      - "5601:5601"
