name: Experiment

on: workflow_dispatch

defaults:
  run:
    working-directory: yona-server

jobs:
  deploy-load-test-server:
    name: Deploy load test server
    environment: load-test
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: /home/bert.roos/.kube/config
    steps:
      - name: Checkout src repo
        uses: actions/checkout@v3
      - name: Install Yona
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_SSH_KEY }}
          script: |
            echo "*** helm repo update"
            helm repo update --debug
            export KUBECONFIG=${{ env.KUBECONFIG }} # Used in Helm and wait-for-services.sh
            export NAMESPACE=loadtest # Used in wait-for-services.sh
            export VALUES_PATH=helm/values_loadtest.yaml
            ENCODED_VALUES_PATH=${VALUES_PATH//\//\%2F} # Replace / with %2F throughout the string
            echo "*** kubectl config use-context beta"
            kubectl config use-context beta
            echo "*** kubectl config set-context --current --namespace=yona"
            kubectl config set-context --current --namespace=yona
            URL="https://git.ops.yona.nu/api/v4/projects/2/repository/files/${ENCODED_VALUES_PATH}/raw?ref=master"
            echo "*** helm upgrade"
            wget --no-verbose --header='PRIVATE-TOKEN: ${{ secrets.YONA_BUILD_GITLAB_TOKEN }}' --output-document=- ${URL} | helm upgrade --wait --install --values - --namespace loadtest --version 1.2.1667 loadtest yona/yona
            echo "*** kubectl get pods"
            kubectl get pods
            echo "*** wait for services"
            wget --no-verbose --output-document=- https://raw.githubusercontent.com/yonadev/yona-server/build-1667/scripts/wait-for-services.sh | bash
