name: Run integration tests

on:
  workflow_dispatch

defaults:
  run:
    working-directory: yona-server

jobs:
  run-int-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: "1635"
#    needs: deploy-int-test-server
#    outputs:
#      build-number: ${{ needs.deploy-int-test-server.outputs.build-number }}
    steps:
      - name: Checkout src repo
        uses: actions/checkout@v2
        with:
          path: 'yona-server'
      - name: Set up JDK 11
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.6.0
        with:
          minikube version: 'v1.25.2'
          kubernetes version: 'v1.24.0'
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.3.0'
      - name: Deploy Yona
        run: |
          helm repo add yona https://yonadev.github.io/helm-charts
          wget -q --output-document=- https://raw.githubusercontent.com/yonadev/yona-server/master/k8s/01_namespace.yaml | kubectl create -f -
          wget -q --output-document=- https://raw.githubusercontent.com/yonadev/yona-server/master/k8s/02_storage.yaml | kubectl create -f -
          helm repo update
          export NAMESPACE=yona # Used in wait-for-services.sh
          cat > values.yml << EOF
          support_infrastructure:
            enabled: true

          mariadb:
            persistence:
            enabled: false

          ldap:
            enabled: false
            storage_class_name_ldap: "hostpath"
            storage_class_name_sldap: "hostpath"

          nodePorts: {}

          admin:
            act_categories_json_file : activityCategories.json

          app:
            max_users: "10000"
            test_server: true
            enable_hibernate_stats_allowed: true
          EOF

          helm upgrade --install --values values.yml --namespace yona --version 1.2.${{ env.BUILD_NUMBER }} yona yona/yona
          # wget --no-verbose --output-document=- https://raw.githubusercontent.com/yonadev/yona-server/build-${{ env.BUILD_NUMBER }}/scripts/wait-for-services.sh | bash
          sleep 120
          kubectl config set-context --current --namespace=yona
          kubectl get deployment
          kubectl get pods
          kubectl get pods --field-selector=status.phase=Pending
          kubectl get StorageClass
          kubectl get PersistentVolume
      - name: Run integration tests
        run: ./gradlew --no-daemon -Pyona_adminservice_url=http://localhost:31000 -Pyona_analysisservice_url=http://localhost:31001 -Pyona_appservice_url=http://localhost:31002 -Pyona_batchservice_url=http://localhost:31003 intTest
      - name: Publish integration test results
        uses: EnricoMi/publish-unit-test-result-action@v1.30
        if: always()
        with:
          files: '**/build/test-results/intTest/*.xml'
